# Generated by Django 3.1.6 on 2021-02-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(verbose_name='Номер страницы')),
                ('main_field', models.TextField(verbose_name='Главное поле')),
                ('name1', models.CharField(max_length=50, verbose_name='Первое имя')),
                ('surname1', models.CharField(max_length=50, verbose_name='Первая фамилия')),
                ('date1', models.IntegerField(verbose_name='Первая дата')),
                ('name2', models.CharField(max_length=50, verbose_name='Второе имя')),
                ('surname2', models.CharField(max_length=50, verbose_name='Вторая фамилия')),
                ('date2', models.IntegerField(verbose_name='Вторая дата')),
                ('name3', models.CharField(max_length=50, verbose_name='Третье имя')),
                ('surname3', models.CharField(max_length=50, verbose_name='Третья фамилия')),
                ('date3', models.IntegerField(verbose_name='Третья дата')),
                ('name4', models.CharField(max_length=50, verbose_name='Четвертое имя')),
                ('surname4', models.CharField(max_length=50, verbose_name='Четвертое фамилия')),
                ('date4', models.IntegerField(verbose_name='Четвертая дата')),
                ('add_field', models.TextField(verbose_name='Поле для спец обозначений')),
                ('text_field', models.TextField(verbose_name='Дополнительное поле')),
                ('company', models.CharField(max_length=200, verbose_name='Название компании')),
            ],
        ),
    ]
